#!/usr/bin/env sh

if ( ! $?SSH_AUTH_SOCK ) then
  eval $(ssh-agent -s)
	/usr/bin/tty | grep 'not a tty' > /dev/null
	if ( ! $status ) then
		ssh-add
	endif
endif

# Fix SSH auth socket location so agent forwarding works within tmux
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi

